# Makefile for {{.ProjectName}}

.PHONY: build start{{if eq .Database "postgresql"}} sqlc{{end}}

# Build the project
build:
	go build -o bin/{{.ProjectName}} ./cmd/{{.ProjectName}}

# Start the project
start:
	{{if eq .Air true}} air {{else}} go run ./cmd/{{.ProjectName}} {{end}}
{{if eq .Database "postgresql"}}
# generate ORM
sqlc:
	sqlc generate
{{end}}
